-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--######################################################################################

-- AUTOGENERATED HYPRLAND CONFIG.

-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

require("monitors")

local colors = dofile(os.getenv("HOME") .. "/.cache/wal/colors-hyprland.lua")

hl.env("QT_STYLE_OVERRIDE", "kvantum")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use

local terminal = "kitty"

local fileManager = "dolphin"

local menu = "wofi --show drun -n"

local browser = "google-chrome-stable"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:

--exec-once = paplay /home/quentu/.config/hypr/sounds/startup_fade.wav



--exec-once = $terminal -e btop

--exec-once = $terminal -e

--exec-once = sleep 2 && $terminal -e sh -c "cd ~/cpond && ./cpond -b -c 2 --fps 60" 



--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

--##################

--## PERMISSIONS ###

--##################

-- See https://wiki.hypr.land/Configuring/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

-- ecosystem {

--   enforce_permissions = 1

-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow

-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 4,
        border_size = 2,
        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
	allow_tearing = false,
        -- layout = "psuedotile",
	col = {
	   active_border   = { colors = {color6, color3}, angle = 45},
	   inactive_border = color7
	},	
        
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 8,
        rounding_power = 4,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1,
        inactive_opacity = 1,
        --0.85
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hypr.land/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 4,
            passes = 4,
            vibrancy = 0.1696,
        },
    },
})

hl.window_rule({
    name  = "waypaper",
    match = {
        class = "waypaper",
    },
    float = true
})

hl.window_rule({
    name  = "dolphin",
    match = {
        class = "dolphin",
    },
    opacity = "1 override 1 override",
})

hl.window_rule({
    name  = "kitty",
    match = {
        class = "kitty",
    },
    opacity = "1 override 0.75 override",
})

hl.layer_rule({
    match = {
        namespace = "waybar",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "waybar",
    },
    ignore_alpha = 0.5,
})

hl.layer_rule({
    match = {
        namespace = "wofi",
    },
    blur = true,
})

hl.layer_rule({
    match = {
	namespace = "wofi",
    },
    ignore_alpha = 0.8,
})

hl.layer_rule({
    match = {
        namespace = "notifications",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "notifications",
    },
    ignore_alpha = 0,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace swayosd",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace swayosd",
    },
    ignore_alpha = 0,
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 750, dampening = 50 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:0, gapsin:0

--workspace = f[1], gapsout:0, gapsin:0

--windowrule {

--     name = no-gaps-wtv1

--     match:float = false

--     match:workspace = w[tv1]

--

--     border_size = 2

--     rounding = 12

--}

--

--windowrule {

--     name = no-gaps-f1

--     match:float = false

--     match:workspace = f[1]

--

--    border_size = 2

--     rounding = 12

--}

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        --    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = 0,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true,
        -- If true disables the random hyprland logo / anime girl background. :(
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            clickfinger_behavior = true,
            tap_to_click = true,
            natural_scroll = false,
            disable_while_typing = false,
        },
    },
})

-- See https://wiki.hypr.land/Configuring/Gestures

-- TODO: manual review: gesture = 3, "horizontal", "workspace"

-- Example per-device config

-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more

-- hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("/crun.sh"))

hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. "+ SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("hyprctl reload"))

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mainMod .. "+ SHIFT" .. " + " .. "M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit"))

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("dolphin"))

--bind = $mainMod, V, togglesplit,

hl.bind(mainMod .. " + SHIFT + RETURN", hl.dsp.exec_cmd("wofi --show drun -n"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.exec_cmd("notify-send \"Super + P\" \"this is bounded to F7\""))

hl.bind(mainMod .. " + " .. "I", hl.dsp.exec_cmd("notify-send \"Super + I\" \"this is bounded to F9\""))

hl.bind("CTRL + ALT" .. " + " .. "Tab", hl.dsp.exec_cmd("notify-send \"Ctrl + Alt + Tab\" \"this is bounded to F11\""))

hl.bind(mainMod .. " + " .. "X", hl.dsp.exec_cmd("~/.config/hypr/scripts/run_xenia.sh"))

hl.bind(mainMod .. "+ SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle-waybar.sh"))

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- dwindle

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("google-chrome-stable"))

hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd("slack"))

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("waypaper"))

hl.bind(mainMod .. "+ SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("hyprshot -m region --freeze"))

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("~/Scripts/Tailscale/tailscale-up.sh"))

hl.bind(mainMod .. "+ SHIFT" .. " + " .. "T", hl.dsp.exec_cmd("~/Scripts/Tailscale/tailscale-down.sh"))

--bind = $mainMod, C, exec, firefox --new-window https://chatgpt.com/

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Move windows with mainMod + SHIFT + arrow keys

hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)

--bind = $mainMod, S, togglespecialworkspace, magic

--bind = $mainMod SHIFT, S, movetoworkspace, special:magic

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

--bindm = $mainMod, mouse:272, movewindow

--bindm = $mainMod, mouse:273, resizewindow

-- hl.bind("$mainMod + CTRL_L + left", hl.dsp.resizeactive("-60 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CTRL_L + up", hl.dsp.resizeactive("0 -60"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CTRL_L + down", hl.dsp.resizeactive("0 60"))

--bind = $mainMod CTRL_L, R, togglesplit

hl.bind("ALT" .. " + " .. "I", hl.dsp.exec_cmd("ydotool mousemove -- 0 -90"))

hl.bind("ALT" .. " + " .. "K", hl.dsp.exec_cmd("ydotool mousemove 0 90"))

hl.bind("ALT" .. " + " .. "J", hl.dsp.exec_cmd("ydotool mousemove -- -90 0"))

hl.bind("ALT" .. " + " .. "L", hl.dsp.exec_cmd("ydotool mousemove 90 0"))

hl.bind("ALT" .. " + " .. "U", hl.dsp.exec_cmd("ydotool click 0xC0"))

hl.bind("ALT + SHIFT" .. " + " .. "O", hl.dsp.exec_cmd("ydotool click 0xC1"))

-- Laptop multimedia keys for volume and LCD brightness

--bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise"), { locked = true })

--bindel = ,XF86AudioRaiseVolume, exec, paplay /home/quentu/.config/hypr/sounds/volume.wav

--bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"), { locked = true })

--bindel = ,XF86AudioLowerVolume, exec, paplay /home/quentu/.config/hypr/sounds/volume.wav

--bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

--bindel = ,XF86AudioMute, exec, swayosd-client --output-volume mute-toggle

hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"))

--bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

--bindel = $mainMod SHIFT, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more

-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules
-- Quentu -

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CTRL_L + right", hl.dsp.resizeactive("600 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)

-- Example windowrules that are useful

hl.window_rule({
    name  = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

-- Hyprland-run windowrule

hl.window_rule({
    name  = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = { 20, "monitor_h-120" },
    float = true,
})

hl.window_rule({
    name  = "ai_popup",
    match = {
        class = "ai_popup",
        float = "yes",
    },
})

hl.window_rule({
    name  = "blueman-manager",
    match = {
        class = "blueman-manager",
    },
    float = true,
    size = { "(monitor_w*0.25)", "(monitor_h*0.25)" },
    opacity = "0.8 0.8",
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waypaper --restore")
    hl.exec_cmd("swayosd-server")
    hl.exec_cmd("paplay ~/.local/share/sounds/startup.ogg")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
end)
